### ISSUE TITLE
LSM

### ISSUE THREAD

**Issue by harryfin3000** [akiratwang/UniMelb-Data-Science#3]
Hi I wasn't sure how to appropriately contact you. Your notes for LSM are amazing! Do you have a copy of the A4 sheet you made for the exam, I'm struggling with what to and what not to include. Thanks

**Comment by akiratwang** [comment]
Hahaha cheers, glad it was of use. I'm afraid whatever is here is all I have!

**Comment by harryfin3000** [comment]
All good
